# Generated by Django 5.1 on 2024-09-01 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('matricula', models.IntegerField()),
                ('senha', models.CharField(max_length=30)),
                ('horasComplementares', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisgehc.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('horasComplementares', models.IntegerField()),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('horaInicio', models.CharField(max_length=30)),
                ('horaFim', models.CharField(max_length=30)),
                ('limiteInscricao', models.IntegerField()),
                ('descricao', models.CharField(max_length=30)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisgehc.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisgehc.aluno')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisgehc.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisgehc.inscricao')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('matricula', models.IntegerField()),
                ('senha', models.CharField(max_length=30)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisgehc.curso')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisgehc.professor'),
        ),
    ]
