# Generated by Django 5.1.1 on 2024-09-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisgehc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
