# Generated by Django 5.1.1 on 2024-09-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisgehc', '0002_evento_imagem_alter_aluno_nome_alter_curso_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='horaFim',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='horaInicio',
            field=models.TimeField(),
        ),
    ]
