# Generated by Django 5.1.1 on 2024-09-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisgehc', '0003_alter_evento_horafim_alter_evento_horainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
    ]
