# Generated by Django 5.1.1 on 2024-09-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sisgehc', '0005_evento_responsavel_alter_evento_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='limiteInscricao',
        ),
    ]
