# Generated by Django 5.1.1 on 2024-09-19 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisgehc', '0006_remove_evento_limiteinscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='professor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sisgehc.professor'),
        ),
    ]
